### ISSUE TITLE
Refactor EventFilter to support Polygon

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/contracts-lib-py#34]
### What

Refactor our event filtering logic so that it does not use the eth filtering api.

### Why

Polygon and maybe other chains don't support the filtering api

### How

Check https://ethereum.stackexchange.com/a/106981/3831 for how to accomplish this

**Comment by aaitor** [comment]
This issue can be deprecated because using the The Graph integration we are gonna pick up the events in a different way
